# Generated by Django 5.1.4 on 2024-12-11 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempoTecnico',
            fields=[
                ('EMP_CodEmpresa', models.CharField(max_length=10, null=True)),
                ('EMP_CodFilial', models.CharField(max_length=10, null=True)),
                ('USR_NomeUsuario', models.CharField(max_length=200, null=True)),
                ('USR_idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('USR_Ativo', models.IntegerField()),
                ('USR_CodAreaOperacao', models.CharField(max_length=10, null=True)),
                ('TMP_Ano', models.IntegerField()),
                ('TMP_Mes', models.IntegerField()),
                ('TMP_MinutosDisponivel', models.FloatField(null=True)),
                ('dthRegistro', models.DateTimeField(blank=True, null=True)),
                ('USR_CodUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos', to='tecnicos.tecnico')),
            ],
        ),
    ]
